### PR TITLE
testing and debugging yolov8_plugin

### PR DESCRIPTION
**Pull request by sanchayvashist**
Tested Yolov8 plugin and made neccesary changes

### CODE REVIEW

**Comment by topguns837** [comment]
Remove this print statement from here : 
https://github.com/atom-robotics-lab/ros-perception-pipeline/blob/7d5b73de84c57eab5aaf6b073ee12bb07419ca0d/object_detection/object_detection/ObjectDetection.py#L108

**Comment by sanchayvashist** [comment]
Incorporated the changes suggested by @topguns837 ,please review the updates

**Comment by topguns837** [comment]
image
@sanchayvashist can you take a look into whether these automatically generated logs can be removed ?

**Comment by sanchayvashist** [comment]
@topguns837 Removed automatically generated logs

**Review by topguns837 — APPROVED** [review]

**Pull request closed without merging**
