### PR TITLE
Added RetinaNet Plugin for `object_detection` package

### PR DESCRIPTION
**Pull request by NOEMOJI041**
- Added RetinaNet Plugin
image

The abundance of bounding boxes in RetinaNet screenshots results from the model's comprehensive exploration of potential object locations, ensuring precise object detection. To address concerns about visual clutter, we are currently developing a thresholding feature. This feature will allow users to set a confidence threshold, displaying only bounding boxes with scores above that threshold, providing a cleaner and more user-friendly experience.

Issue #8

### CODE REVIEW

**Comment by NOEMOJI041** [comment]
The abundance of bounding boxes in RetinaNet screenshots results from the model's comprehensive exploration of potential object locations, ensuring precise object detection. To address concerns about visual clutter, we are currently developing a thresholding feature. This feature will allow users to set a confidence threshold, displaying only bounding boxes with scores above that threshold, providing a cleaner and more user-friendly experience.

**Comment by topguns837** [comment]
@NOEMOJI041 I have checked the P.R., everything works but please remove these print statements 
image

**Comment by NOEMOJI041** [comment]
> @NOEMOJI041 I have checked the P.R., everything works but please make these small changes :
> 
> 1. Remove these print statements
>    image
> 2. Remove the unecessary imports from https://github.com/atom-robotics-lab/ros-perception-pipeline/blob/c1aaa09de3b93f991217b45b4a4c77fa1c4afcc3/object_detection/object_detection/Detectors/RetinaNet.py#L6C2-L6C2
>    image

1. Print statement is present in ObjectDetection.py file to remove, we need to make changes in the ObjectDetection.py file this PR is concentrated on changes related to RetinaNet we can create an issue for the same.
2. Removed Unwanted Imports in commit [4f2a307](https://github.com/atom-robotics-lab/ros-perception-pipeline/pull/37/commits/4f2a30786dae34e938948aaf759d7cd25a98c5cf)

**Comment by topguns837** [comment]
Good job @NOEMOJI041 . Merging the branches

**Pull request merged**
